// src/components/Login.tsx
import React, { ReactElement, useState } from 'react';

export interface Props {
  onSubmit: () => void;
}

function Login(props: Props): ReactElement {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  return (
    <form className="user-form" action="/register" method="POST">
      <div className="form-group">
        <label className="form-label">Username</label>
        <input
          className="form-control"
          aria-describedby="text"
          onChange={(e) => setUsername(e.target.value)}
          value={username}
        />
      </div>
      <div className="form-group">
        <label className="form-label">Password</label>
        <input
          type="password"
          className="form-control"
          onChange={(e) => setPassword(e.target.value)}
          value={password}
        />
      </div>
      <button
        type="submit"
        className="btn btn-lg btn-outline-light"
        onClick={(e) => {
          props.onSubmit();
          e.preventDefault();
        }}>
        Register
      </button>
    </form>
  );
}

export default Login;

// src/app/login/login.component.ts
import { Router } from '@angular/router';
import { UserService } from './../user.service';
import { ApiService } from './../api.service';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent implements OnInit {
  username: string;
  password: string;
  constructor(
    private apiService: ApiService,
    private userService: UserService,
    private router: Router
  ) {}

  onPress() {
    this.apiService
      .login(this.username, this.password)
      .toPromise()
      .then((res) => {
        this.userService.login(this.username);
        this.router.navigateByUrl('/home');
      })
      .catch((error) => {
        console.log(error);
      });
  }

  ngOnInit(): void {}
}

<form class="user-form" action="/login" method="POST">
  <div class="form-group">
    <label class="form-label" for="email">Username</label>
    <input
      type="username"
      class="form-control"
      name="email"
      [(ngModel)]="username"
    />
  </div>
  <div class="form-group">
    <label class="form-label" for="password">Password</label>
    <input
      type="password"
      name="password"
      class="form-control"
      [(ngModel)]="password"
    />
  </div>
  <button
    type="submit"
    (click)="onPress()"
    class="btn btn-lg btn-outline-light"
  >
    Login
  </button>
</form>
