// src/app/navbar/navbar.component.ts
import { UserService } from './../user.service';
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css'],
})
export class NavbarComponent implements OnInit {
  @Input() links: navbarLink[];

  public loggedOutLinks: navbarLink[] = [
    { name: 'About', href: '' },
    { name: 'Register', href: 'register' },
    { name: 'Login', href: 'login' },
  ];

  public loggedInLinks: navbarLink[] = [
    { name: 'Home', href: 'home' },
    { name: 'Create', href: 'create' },
    { name: 'Logout', href: 'logout' },
  ];

  constructor(public userService: UserService) {}

  ngOnInit(): void {}
}

export interface navbarLink {
  name: string;
  href: string;
}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">One Deed a Day</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <div
        *ngIf="userService.isLoggedIn(); then loggedIn; else loggedOut"
      ></div>
    </ul>

    <ng-template #loggedIn>
      <li *ngFor="let link of loggedInLinks" class="nav-item">
        <a class="nav-link" routerLink="{{ link.href }}">{{ link.name }}</a>
      </li>
    </ng-template>

    <ng-template #loggedOut>
      <li *ngFor="let link of loggedOutLinks" class="nav-item">
        <a class="nav-link" routerLink="{{ link.href }}">{{ link.name }}</a>
      </li>
    </ng-template>
  </div>
</nav>

// src/components/Navbar.tsx
import React, { ReactElement } from 'react';

export interface Link {
  name: string;
  url: string;
  active?: boolean;
}

export interface Props {
  links: {
    linkOne: Link;
    linkTwo: Link;
    linkThree: Link;
  };
}

function Navbar(props: Props): ReactElement {
  return (
    <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
      <a className="navbar-brand" href="/">
        One Deed a Day
      </a>
      <button
        className="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span className="navbar-toggler-icon"></span>
      </button>

      <div className="collapse navbar-collapse" id="navbarSupportedContent">
        <ul className="navbar-nav ml-auto">
          <li className="nav-item">
            <a
              className={`nav-link ${props.links.linkOne.active && 'active'}`}
              href={props.links.linkOne.url}
            >
              {props.links.linkOne.name}
            </a>
          </li>
          <li className="nav-item">
            <a
              className={`nav-link ${props.links.linkTwo.active && 'active'}`}
              href={props.links.linkTwo.url}
            >
              {props.links.linkTwo.name}
            </a>
          </li>
          <li className="nav-item">
            <a className="nav-link" href={props.links.linkThree.url}>
              {props.links.linkThree.name}
            </a>
          </li>
        </ul>
      </div>
    </nav>
  );
}

export default Navbar;
